### ISSUE TITLE
Morning Session: Code Review

### ISSUE THREAD

**Issue by faizi2500** [mmatongo/portfolio-project#15]
##Amazing Job With The Project## 

There are few suggestions that we in the morning session came up with that you can implement in your project:

-  We noticed that you have used pixel to set your font sizes. Its better to use rem, instead, so it adjust to different user browser custom font sizes. 
- You were using images as for your social icons. We think it is better to use icons.: Font Awesome or HTML entities could be used.
- Add hover effect to your "Get My Resume" button. This will make your website more user interactive
- Footer input fields are too wide and that is why they are covering the background image. You can reduce the width to avoid overlapping. Also reduce the vertical gaps between them.
- Increase the size of the buttons for mobile modal version so they are close to each other. Currently they are both on the opposite extremes. 

What you've done so far is just awesome 👌🏼 
These are just few suggestions that you can incorporate in your project template. Cheers and Happy coding!!

**Comment by mmatongo** [comment]
Thank you for the feedback.
